/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'luisc' at '6/1/16 2:30 AM' with Gradle 2.12
 *
 * @author luisc, @date 6/1/16 2:30 AM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
